// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoihuWQVNcK_wxyrY3YHr_F-qdICqmu0s',
    appId: '1:227174572060:web:e1548fb0e1234c0f353fd9',
    messagingSenderId: '227174572060',
    projectId: 'flutter-hands-on-86237',
    authDomain: 'flutter-hands-on-86237.firebaseapp.com',
    storageBucket: 'flutter-hands-on-86237.appspot.com',
    measurementId: 'G-ERPQ13WKXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrzolGRWQPLXugvdi1O-qmAfcu4wP5hOI',
    appId: '1:227174572060:android:2f697f1b6392b469353fd9',
    messagingSenderId: '227174572060',
    projectId: 'flutter-hands-on-86237',
    storageBucket: 'flutter-hands-on-86237.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCybzgUvlZHUvtmVdXu8Tv-NxWu3MWNLbI',
    appId: '1:227174572060:ios:25f911745d799c61353fd9',
    messagingSenderId: '227174572060',
    projectId: 'flutter-hands-on-86237',
    storageBucket: 'flutter-hands-on-86237.appspot.com',
    iosClientId: '227174572060-bem7bbo8fo3u17agn5eg3kt6eit3ljii.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHandsOn',
  );
}
